### ISSUE TITLE
Add Loading animation

### ISSUE THREAD

**Issue by hmallen99** [hmallen99/hmallen99.github.io#24]
```css
.project-content {
  animation: fade-in 1s;
}

@keyframes fade-in {
  from {
    opacity: 0;
  }
  to {
    opacity: 100;
  }
}
```

```ts
import React, { useState, useEffect } from 'react';

function MyComponent() {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    setIsVisible(true);
  }, []);

  return (
    <div className={`my-component ${isVisible ? 'fade-in' : ''}`}>
      {/* Your content */}
    </div>
  );
}
```
